CREATE TABLE IF NOT EXISTS `toffres` (
	`codeCGT` varchar(20) NOT NULL,
	`nom` varchar(255) DEFAULT NULL,
	`nom_nl` varchar(255) DEFAULT NULL,
	`nom_en` varchar(255) DEFAULT NULL,
	`nom_de` varchar(255) DEFAULT NULL,
	`cplt_nom` varchar(255) DEFAULT NULL,
	`bce` varchar(255) DEFAULT NULL,
	`rue` varchar(255) DEFAULT NULL,
	`rue_cplt` varchar(255) DEFAULT NULL,
	`numero` varchar(255) DEFAULT NULL,
	`boite` varchar(45) DEFAULT NULL,
	`cp` varchar(20) DEFAULT NULL,
	`id_ins` INT DEFAULT NULL,
	`ins` varchar(20) DEFAULT NULL,
	`lieu_dit` varchar(255) DEFAULT NULL,
	`lieu_precis` varchar(255) DEFAULT NULL,
	`localite` varchar(100) DEFAULT NULL,
	`commune` varchar(100) DEFAULT NULL,
	`province` varchar(45) DEFAULT NULL,
	`parc_naturel` varchar(100) DEFAULT NULL,
	`mdt` varchar(100) DEFAULT NULL,
	`coord_lambert_x` FLOAT DEFAULT NULL,
	`coord_lambert_y` FLOAT DEFAULT NULL,
	`coord_geo_longitude` FLOAT DEFAULT NULL,
	`coord_geo_latitude` FLOAT DEFAULT NULL,
	`itineraire_acces` TEXT DEFAULT NULL,
	`itineraire_acces_nl` TEXT DEFAULT NULL,
	`itineraire_acces_en` TEXT DEFAULT NULL,
	`itineraire_acces_de` TEXT DEFAULT NULL,
	`qualite` varchar(30) DEFAULT NULL,
	`classement` varchar(30) DEFAULT NULL,
	`classement_num` INT(1) DEFAULT NULL,
	`capacite1` INT DEFAULT NULL,
	`capacite2` INT DEFAULT NULL,
	`nbr_chambre` INT DEFAULT NULL,
	`nbr_unite_sejour` INT DEFAULT NULL,
	`descriptif` TEXT DEFAULT NULL,
	`descriptif_nl` TEXT DEFAULT NULL,
	`descriptif_en` TEXT DEFAULT NULL,
	`descriptif_de` TEXT DEFAULT NULL,
	`complement_tarif` TEXT DEFAULT NULL,
	`complement_tarif_nl` TEXT DEFAULT NULL,
	`complement_tarif_en` TEXT DEFAULT NULL,
	`complement_tarif_de` TEXT DEFAULT NULL,
	`descriptif_groupes` TEXT DEFAULT NULL,
	`descriptif_groupes_nl` TEXT DEFAULT NULL,
	`descriptif_groupes_en` TEXT DEFAULT NULL,
	`descriptif_groupes_de` TEXT DEFAULT NULL,
	`descriptif_indiv` TEXT DEFAULT NULL,
	`descriptif_indiv_nl` TEXT DEFAULT NULL,
	`descriptif_indiv_en` TEXT DEFAULT NULL,
	`descriptif_indiv_de` TEXT DEFAULT NULL,
	`descriptif_rando` TEXT DEFAULT NULL,
	`descriptif_rando_nl` TEXT DEFAULT NULL,
	`descriptif_rando_en` TEXT DEFAULT NULL,
	`descriptif_rando_de` TEXT DEFAULT NULL,
	`descriptif_scolaire` TEXT DEFAULT NULL,
	`descriptif_scolaire_nl` TEXT DEFAULT NULL,
	`descriptif_scolaire_en` TEXT DEFAULT NULL,
	`descriptif_scolaire_de` TEXT DEFAULT NULL,
	`horaire_ouverture` TEXT DEFAULT NULL,
	`horaire_ouverture_nl` TEXT DEFAULT NULL,
	`horaire_ouverture_en` TEXT DEFAULT NULL,
	`horaire_ouverture_de` TEXT DEFAULT NULL,
	`horaire_ouverture_groupes` TEXT DEFAULT NULL,
	`horaire_ouverture_groupes_nl` TEXT DEFAULT NULL,
	`horaire_ouverture_groupes_en` TEXT DEFAULT NULL,
	`horaire_ouverture_groupes_de` TEXT DEFAULT NULL,
	`points_forts` TEXT DEFAULT NULL,
	`points_forts_nl` TEXT DEFAULT NULL,
	`points_forts_en` TEXT DEFAULT NULL,
	`points_forts_de` TEXT DEFAULT NULL,
	`metadonnees_resume` TEXT DEFAULT NULL,
	`metadonnees_resume_nl` TEXT DEFAULT NULL,
	`metadonnees_resume_en` TEXT DEFAULT NULL,
	`metadonnees_resume_de` TEXT DEFAULT NULL,
	`metadonnees_motscles` TEXT DEFAULT NULL,
	`metadonnees_motscles_nl` TEXT DEFAULT NULL,
	`metadonnees_motscles_en` TEXT DEFAULT NULL,
	`metadonnees_motscles_de` TEXT DEFAULT NULL,
	`pmr_acceptes` TINYINT(1) DEFAULT NULL,
	`groupes_acceptes` TINYINT(1) DEFAULT NULL,
	`animaux_admis` TINYINT(1) DEFAULT NULL,
	`non_fumeur` TINYINT(1) DEFAULT NULL,
	`date_creation` datetime DEFAULT NULL,
	`date_modification` datetime DEFAULT NULL,
	`fk_ttypesoffres_id_type_offre` INT NOT NULL,
	`fk_toffres_codeCGT` VARCHAR(20) DEFAULT NULL,
	`fk_toffres_codeCGT_mdt` VARCHAR(20) DEFAULT NULL,
	`id_atoms` VARCHAR(255) DEFAULT NULL,
    `code_interne_CGT` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`codeCGT`),
	KEY `fk_ttypesoffres_id_type_offre` (`fk_ttypesoffres_id_type_offre`),
	KEY `fk_toffres_codeCGT` (`fk_toffres_codeCGT`),
	KEY `fk_toffres_codeCGT_mdt` (`fk_toffres_codeCGT_mdt`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS `tchambres` (
	`id_chambre` INT NOT NULL,
	`denomination` VARCHAR(255) DEFAULT NULL,
	`nb_lits_single` INT DEFAULT NULL,
	`nb_lits_double` INT DEFAULT NULL,
	`nb_lits_sup` INT DEFAULT NULL,
	`nb_lits_bebe` INT DEFAULT NULL,
	`salle_sdd` TINYINT(1) DEFAULT NULL,
	`salle_sdb` TINYINT(1) DEFAULT NULL,
	`wc` TINYINT(1) DEFAULT NULL,
	`complement_info` TEXT DEFAULT NULL,
	`complement_info_nl` TEXT DEFAULT NULL,
	`complement_info_en` TEXT DEFAULT NULL,
	`complement_info_de` TEXT DEFAULT NULL,
	`fk_toffres_codeCGT` VARCHAR(20) NOT NULL,
	PRIMARY KEY (`id_chambre`),
	KEY `fk_toffres_codeCGT` (`fk_toffres_codeCGT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
CREATE TABLE IF NOT EXISTS `thebergements` (
	`codeCGT` VARCHAR(20) NOT NULL,
	`chambre_1p` TINYINT(1) DEFAULT NULL,
	`chambre_2p` TINYINT(1) DEFAULT NULL,
	`chambre_3p` TINYINT(1) DEFAULT NULL,
	`chambre_4p` TINYINT(1) DEFAULT NULL,
	`nbr_lits_sup` INT DEFAULT NULL,
	`nbr_lits_simple` INT DEFAULT NULL,
	`nbr_lits_double` INT DEFAULT NULL,
	`nbr_lits_superpose` INT DEFAULT NULL,
	`cuisine_sep` TINYINT(1) DEFAULT NULL,
	`sam_sep` TINYINT(1) DEFAULT NULL,
	`salon_sep` TINYINT(1) DEFAULT NULL,
	`sam_salon` TINYINT(1) DEFAULT NULL,
	`nbr_sdeau` INT DEFAULT NULL,
	PRIMARY KEY (`codeCGT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
CREATE TABLE `tcontacts` (
  `id_contact` int(11) NOT NULL,
  `civilite` varchar(100) DEFAULT NULL,
  `nom` varchar(255) DEFAULT NULL,
  `prenom` varchar(255) DEFAULT NULL,
  `adresse` varchar(255) DEFAULT NULL,
  `numero` varchar(255) DEFAULT NULL,
  `boite` varchar(20) DEFAULT NULL,
  `id_ins` int(11) DEFAULT NULL,
  `ins` varchar(20) DEFAULT NULL,
  `cp` varchar(40) DEFAULT NULL,
  `localite` varchar(255) DEFAULT NULL,
  `commune` varchar(255) DEFAULT NULL,
  `telephone` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `gsm` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_contact`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `ttarifs` (
  `id_tarif` int(11) NOT NULL,
  `categorie` int(1) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `type_nl` varchar(255) DEFAULT NULL,
  `type_en` varchar(255) DEFAULT NULL,
  `type_de` varchar(255) DEFAULT NULL,
  `complement_info` text,
  `complement_info_nl` text,
  `complement_info_en` text,
  `complement_info_de` text,
  `date` date DEFAULT NULL,
  `prix_min` float DEFAULT NULL,
  `prix_max` float DEFAULT NULL,
  `fk_toffres_codeCGT` varchar(20) NOT NULL,
  PRIMARY KEY (`id_tarif`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;
CREATE TABLE `treloffrecontact` (
  `fk_toffres_codeCGT` varchar(20) NOT NULL,
  `fk_tcontacts_id_contact` int(11) NOT NULL,
  `type` varchar(255) NOT NULL,
  `type_nl` varchar(255) DEFAULT NULL,
  `type_en` varchar(255) DEFAULT NULL,
  `type_de` varchar(255) DEFAULT NULL,
  KEY `fk_toffres_codeCGT` (`fk_toffres_codeCGT`),
  KEY `fk_tcontacts_id_contact` (`fk_tcontacts_id_contact`),
  CONSTRAINT `treloffrecontact_ibfk_2` FOREIGN KEY (`fk_tcontacts_id_contact`) REFERENCES `tcontacts` (`id_contact`),
  CONSTRAINT `treloffrecontact_ibfk_1` FOREIGN KEY (`fk_toffres_codeCGT`) REFERENCES `toffres` (`codeCGT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
